# -*- coding: utf-8 -*-
"""analytics_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136lLxI0d9pOaZsj98eeIlqY83msZZyeL
"""

import pandas as pd
import numpy as np
from datetime import datetime
from typing import Optional

def generate_monthly_summary(df: pd.DataFrame, month: int, year: int) -> dict:
    df = df.copy()
    df['Date'] = pd.to_datetime(df['Date'])
    mask = (df['Date'].dt.month == month) & (df['Date'].dt.year == year)
    mdf = df[mask]
    
    exp = mdf[mdf['Transaction_Type'] == 'Expense']
    inc = mdf[mdf['Transaction_Type'] == 'Income']
    
    total_expense = float(exp['Amount'].sum())
    total_income = float(inc['Amount'].sum())
    
    top_cat = "-"
    if not exp.empty:
        cat_sums = exp.groupby('Category')['Amount'].sum()
        if not cat_sums.empty:
            top_cat = str(cat_sums.idxmax())
            
    period = datetime(year, month, 1).strftime('%B %Y')
    
    return {
        "total_expense": total_expense,
        "total_income": total_income,
        "top_category": top_cat,
        "period": period
    }


def main():
    df = pd.read_csv(r"C:\Users\Aditya P J\Documents\Magang dan Lisensi\BoothCamp\CapStone\data\Data_Final_Combine.csv")
    df.head()

    df.info()

    df['Date'] = pd.to_datetime(df['Date'])

    """1. **Is_Weekend**-Perilaku akhir pekan
    2. **Week**-Analisis mingguan
    3. **Daily_Total**-Total per hari
    4. **Category_Ratio**-% per kategori
    5. **Expense_Level**-Low / Medium / High
    6. **Transaction_Count**-Frekuensi transaksi
    """

    # 1. Is_weekend
    # True Jika Sabtu (5) atau Minggu (6)
    df['Is_Weekend'] = df['Date'].dt.dayofweek.isin([5, 6])

    # 2. Week
    # Nomor minggu dalam tahun (ISO week Number)
    df['Week'] = df['Date'].dt.isocalendar().week

    # 3. Daily_Total
    # Total Amount per tanggal, di-map kembali ke setiap baris
    df['Daily_Total'] = df.groupby('Date')['Amount'].transform('sum')

    # 4. Catgory_Ratio
    # Persentase Amount tiap baris terhadap total kategorinya
    category_total = df.groupby('Category')['Amount'].transform('sum')
    df['Category_Ratio'] = (df['Amount'] / category_total * 100).round(2)

    df.describe()

    # 5. Exspense_Level
    # Klasifikasi berdasarkan persentil 33 dan 67
    q33 = df['Amount'].quantile(0.33)
    q67 = df['Amount'].quantile(0.67)

    df['Expense_Level'] = pd.cut(
        df['Amount'],
        bins=[-np.inf, q33, q67, np.inf],
        labels=['Low', 'Medium', 'High']
    )

    #  6. Transaction_Count
    # Jumlah transaksi per tanggal
    df['Transaction_Count'] = df.groupby('Date')['Amount'].transform('count')

    # Verifikasi hasil
    print(df[['Date', 'Amount', 'Is_Weekend', 'Week',
              'Daily_Total', 'Category_Ratio',
              'Expense_Level', 'Transaction_Count']].head(10))

    print(f"\nShape baru : {df.shape}")
    print(f"\nDistribusi Expense_Level:")
    print(df['Expense_Level'].value_counts())

if __name__ == "__main__":
    main()

